name: "Entando CI Docker images"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled
    branches:
      - develop
      - release/*
  push:
    tags:
      - "v*"
    branches:
      - develop
      - release/*
      - ENG-*
      - ENGPM-*
      - IT-*

permissions: write-all

jobs:
  check-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' || github.event_name == 'pull_request' }}
    permissions: write-all
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"

  docker-buildx:
    name: Buildx
    runs-on: ubuntu-latest
    if: check-pr == 'success' || github.event_name != 'pull_request_target'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta-keycloak
        id: meta-keycloak
        uses: docker/metadata-action@v4
        with:
          # List of Docker Images to use as base name for tags
          images: |
            pmasala/kc
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,value={{head_ref}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{head_ref}}

      - name: Docker meta-sso
        id: meta-sso
        uses: docker/metadata-action@v4
        with:
          # List of Docker Images to use as base name for tags
          images: |
            pmasala/sso
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to RHT
        uses: docker/login-action@v2
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHT_DOCKER_USERNAME }}
          password: ${{ secrets.RHT_DOCKER_TOKEN }}

      - name: Build keycloak
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.keycloak
          push: true
          tags: ${{ steps.meta-keycloak.outputs.tags }}
          labels: ${{ steps.meta-keycloak.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Build sso
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.redhat-sso
          push: true
          tags: ${{ steps.meta-sso.outputs.tags }}
          labels: ${{  steps.meta-sso.outputs.labels }}
          platforms: linux/amd64
