name: Build Multi-arch Docker images

on:
  pull_request:
    types:
      - opened
      - synchronized
      - reopened
    branches:
      - develop
      - release/*

jobs:
    buildx:
      name: Buildx
      runs-on: ubuntu-latest
      steps:

      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        name: Build keycloak
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.keycloak
          push: true
          tags: "pmasala/kc:$GITHUB_REF_NAME"
          platforms: linux/amd64,linux/arm64
