name: "Entando CI Docker images"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - labeled
      - unlabeled
    branches:
      - develop
      - release/*

permissions: write-all

jobs:
  check-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' || github.event_name == 'pull_request' }}
    permissions: write-all
    steps:
      - name: Check-pr-syntax
        uses: thehanimo/pr-title-checker@v1.3.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"
